### ISSUE TITLE
When will open source be available

### ISSUE THREAD

**Issue by ShockCloud10** [BaoGuangYin/PmcmFL#1]
Hi Bro
When will open source be available? Looking forward to this work 👍 :)

**Comment by BaoGuangYin** [comment]
Thank you for your interest in our work. Unfortunately, our work has just recently been rejected by ICML2024 and we are currently preparing to move to another journal.
Once it is accepted, we will open source our code immediately.

**Comment by BaoGuangYin** [comment]
If you are interested in multimodal federated learning, we would love to connect with you. Please reach out to us via email for further communication. ^^
